import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootLayoutWrapper from "@/components/pages/Wrapper/RootLayoutWrapper";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Providers } from "@/providers/Providers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Blueprint - A professional real estate company",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ReactQueryProvider>
                    <Providers>
                        <RootLayoutWrapper>{children}</RootLayoutWrapper>
                    </Providers>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
